name: Playwright Tests
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install root dependencies
        run: npm ci 

      - name: Install app dependencies
        run: npm ci --prefix localdevserver/cinema-scheduler-master

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Pages Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 'github-pages'
          path: 'playwright-report/'
          retention-days: 30

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v5
        if: always()
